name: dartzmq
description: A simple dart zeromq implementation/wrapper around the libzmq C++ library
version: 1.0.0-dev.15
homepage: https://github.com/enwi/dartzmq
repository: https://github.com/enwi/dartzmq

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  ffi: ">=2.0.0"

dev_dependencies:
   ffi: ^2.0.1
   ffigen: ">=4.1.2"

